import type { ControlGate, DomainCard, ModuleCard, Stream, WorkflowStage } from './types'

export const streams: Stream[] = [
  { key: 'sale', label: 'Sale Intake', short: 'SL', summary: 'Tiep nhan nhu cau va chot input ky thuat.' },
  { key: 'rnd', label: 'R&D Control', short: 'RD', summary: 'Quan ly cong thuc, version va phat hanh du lieu ky thuat.' },
  { key: 'planning', label: 'Planning & Purchase', short: 'PP', summary: 'Lap ke hoach, chay MRP, tao PO va hoa don dau vao.' },
  { key: 'warehouse', label: 'Warehouse LOT', short: 'WH', summary: 'Nhap kho theo LOT, theo tai lieu ky thuat va cap phat.' },
  { key: 'quality', label: 'QC / QA Gates', short: 'QA', summary: 'Chan mo rong neu LOT, IPC hay thanh pham khong dat.' },
  { key: 'production', label: 'Production Flow', short: 'PX', summary: 'Lenh SX, batch record, san xuat, dong goi va nhap kho.' },
  { key: 'closure', label: 'Trace & Closure', short: 'TR', summary: 'Dong ho so lo, truy xuat, CAPA va san sang audit.' },
]

export const workflowStages: WorkflowStage[] = [
  {
    id: '01',
    stream: 'sale',
    owner: 'Sale',
    title: 'Tiep nhan yeu cau khach hang',
    input: 'Khach hang, loai san pham, cong dung, dung tich, so luong.',
    output: 'Yeu cau ky thuat du dieu kien chuyen R&D.',
    control: 'Thieu thong tin bat buoc thi khong duoc chuyen buoc.',
    gate: 'hard',
  },
  {
    id: '02',
    stream: 'rnd',
    owner: 'R&D',
    title: 'Tao cong thuc va kiem tra tai lieu',
    input: 'Yeu cau Sale va du lieu nguyen lieu.',
    output: 'Cong thuc, quy trinh, chi tieu ky thuat.',
    control: 'Thieu COA/MSDS/TDS/IFRA thi chan, nguyen lieu moi can CEO duyet.',
    gate: 'hard',
  },
  {
    id: '03',
    stream: 'rnd',
    owner: 'R&D',
    title: 'Phat hanh du lieu ky thuat',
    input: 'Cong thuc da duyet.',
    output: 'Version approved, dinh muc R&D, mapping GMP va ke toan.',
    control: 'Chi version approved moi duoc su dung xuong cac module sau.',
    gate: 'flow',
  },
  {
    id: '04',
    stream: 'planning',
    owner: 'Planning',
    title: 'Lap ke hoach san xuat',
    input: 'Cong thuc approved va ton kho hien tai.',
    output: 'Ke hoach san xuat va de xuat mua.',
    control: 'Thieu nguyen lieu thi bat buoc sinh purchase suggestion.',
    gate: 'flow',
  },
  {
    id: '05',
    stream: 'planning',
    owner: 'Purchasing',
    title: 'Mua hang va nhan hoa don',
    input: 'Purchase suggestion tu planning.',
    output: 'PO, theo doi giao hang va hoa don NCC.',
    control: 'Hoa don thieu khong chan cung, nhung se thanh soft block o cap phat.',
    gate: 'soft',
  },
  {
    id: '06',
    stream: 'warehouse',
    owner: 'Warehouse',
    title: 'Nhap kho nguyen lieu theo LOT',
    input: 'PO, lo hang ve kho va tai lieu kem theo.',
    output: 'Material LOT va ho so ky thuat LOT.',
    control: 'Thieu tai lieu ky thuat thi canh bao do va cho QC.',
    gate: 'flow',
  },
  {
    id: '07',
    stream: 'quality',
    owner: 'QC',
    title: 'QC dau vao',
    input: 'LOT vua nhap kho.',
    output: 'Ket qua dat / khong dat va bien ban lien quan.',
    control: 'Khong dat thi chan su dung nguyen lieu.',
    gate: 'hard',
  },
  {
    id: '08',
    stream: 'quality',
    owner: 'QA',
    title: 'QA duyet LOT',
    input: 'Ket qua QC incoming.',
    output: 'LOT dat / giu / loai.',
    control: 'LOT chua QA duyet thi khong duoc cap phat.',
    gate: 'hard',
  },
  {
    id: '09',
    stream: 'production',
    owner: 'Production',
    title: 'Tao lenh san xuat',
    input: 'Cong thuc approved va LOT dat.',
    output: 'Work order san sang release.',
    control: 'Thieu cong thuc hoac LOT dat thi chan.',
    gate: 'hard',
  },
  {
    id: '10',
    stream: 'production',
    owner: 'Production',
    title: 'Phat hanh batch record',
    input: 'Lenh san xuat da release.',
    output: 'Ho so lo GMP va checklist khoa dinh muc.',
    control: 'Sau release thi dinh muc GMP phai bi khoa.',
    gate: 'flow',
  },
  {
    id: '11',
    stream: 'warehouse',
    owner: 'Warehouse',
    title: 'Cap phat nguyen lieu theo LOT',
    input: 'Batch record va danh sach LOT du dieu kien.',
    output: 'Dispensing va ghi nhan su dung cho batch.',
    control: 'LOT khong dat bi chan cung, invoice thieu la soft block can CEO duyet.',
    gate: 'soft',
  },
  {
    id: '12',
    stream: 'production',
    owner: 'Production',
    title: 'San xuat ban thanh pham',
    input: 'Nguyen lieu da cap phat.',
    output: 'Du lieu thuc te san xuat va hao hut.',
    control: 'Lech dinh muc thi canh bao ngay tren execution.',
    gate: 'flow',
  },
  {
    id: '13',
    stream: 'quality',
    owner: 'QC',
    title: 'IPC trong qua trinh',
    input: 'Thong so va mau tai cong doan.',
    output: 'Cho phep / chan cong doan tiep.',
    control: 'IPC fail thi khong duoc di tiep.',
    gate: 'hard',
  },
  {
    id: '14',
    stream: 'production',
    owner: 'Packaging',
    title: 'Dong goi',
    input: 'Ban thanh pham dat IPC.',
    output: 'Thanh pham dong goi theo quy cach.',
    control: 'Sai bao bi thi chan cong doan.',
    gate: 'hard',
  },
  {
    id: '15',
    stream: 'quality',
    owner: 'QC',
    title: 'QC thanh pham',
    input: 'Mau thanh pham sau dong goi.',
    output: 'Ket qua dat / khong dat.',
    control: 'Khong dat thi khong nhap kho thanh pham.',
    gate: 'hard',
  },
  {
    id: '16',
    stream: 'quality',
    owner: 'QA',
    title: 'QA duyet thanh pham',
    input: 'Ket qua QC thanh pham.',
    output: 'Batch duoc phep release.',
    control: 'Chi batch duyet dat moi duoc nhap kho.',
    gate: 'hard',
  },
  {
    id: '17',
    stream: 'warehouse',
    owner: 'FG Warehouse',
    title: 'Nhap kho thanh pham',
    input: 'Batch da QA release.',
    output: 'Ton kho thanh pham theo batch.',
    control: 'Ghi nhan inventory rieng, khong gop voi hoa don.',
    gate: 'flow',
  },
  {
    id: '18',
    stream: 'closure',
    owner: 'Logistics',
    title: 'Giao hang',
    input: 'Thanh pham co san va lenh giao.',
    output: 'Delivery va mapping batch giao cho khach.',
    control: 'Can truy xuat batch giao theo khach hang.',
    gate: 'flow',
  },
  {
    id: '19',
    stream: 'closure',
    owner: 'QA / Compliance',
    title: 'Dong ho so lo',
    input: 'Checklist batch record va chung tu lien quan.',
    output: 'Ho so lo duoc dong va khoa du lieu.',
    control: 'Ho so chua day du thi khong duoc dong.',
    gate: 'close',
  },
  {
    id: '20',
    stream: 'closure',
    owner: 'Compliance',
    title: 'Truy xuat, CAPA, thu hoi',
    input: 'Thanh pham, batch, LOT, NCC, invoice.',
    output: 'Bao cao audit-ready va chuoi truy xuat hoan chinh.',
    control: 'Ho tro GMP inspection, recall va kiem toan.',
    gate: 'flow',
  },
]

export const moduleCards: ModuleCard[] = [
  {
    id: 'sales-request',
    stream: 'sale',
    title: 'Sale Request Module',
    screens: 'Danh sach yeu cau, tao moi, chi tiet va submit.',
    api: 'POST /api/sales-requests',
    db: 'sales_requests, sales_request_items',
  },
  {
    id: 'formula',
    stream: 'rnd',
    title: 'R&D Formula Module',
    screens: 'Workspace cong thuc, BOM theo LOT, trinh duyet.',
    api: 'POST /api/formulas/:id/approve',
    db: 'formulas, formula_versions, formula_components',
  },
  {
    id: 'technical-release',
    stream: 'rnd',
    title: 'Technical Release Module',
    screens: 'Phat hanh du lieu ky thuat va lich su version.',
    api: 'POST /api/technical-releases/:id/publish',
    db: 'technical_releases, spec_snapshots',
  },
  {
    id: 'planning',
    stream: 'planning',
    title: 'Production Planning Module',
    screens: 'Ke hoach ngay/tuan/thang, MRP check, de xuat mua.',
    api: 'POST /api/production-plans/:id/run-mrp',
    db: 'production_plans, material_requirements',
  },
  {
    id: 'purchasing',
    stream: 'planning',
    title: 'Purchasing Module',
    screens: 'Danh sach de xuat mua, PO, giao hang, hoa don.',
    api: 'POST /api/purchase-orders/:id/receive',
    db: 'purchase_orders, vendor_invoices',
  },
  {
    id: 'warehouse-lot',
    stream: 'warehouse',
    title: 'Warehouse Inbound LOT Module',
    screens: 'Nhap kho theo LOT, upload tai lieu, cho QC.',
    api: 'POST /api/material-lots/:id/attach-documents',
    db: 'material_lots, lot_documents, inventory_transactions',
  },
  {
    id: 'dispensing',
    stream: 'warehouse',
    title: 'Material Dispensing Module',
    screens: 'Cap phat theo LOT, canh bao lot khong dat, chot cap phat.',
    api: 'POST /api/dispensings/:id/confirm',
    db: 'dispensings, dispensing_lines, dispensing_exceptions',
  },
  {
    id: 'qc-incoming',
    stream: 'quality',
    title: 'QC Incoming Module',
    screens: 'Queue LOT, form ket qua QC, bien ban nonconformity.',
    api: 'POST /api/qc-incoming-results/:id/finalize',
    db: 'qc_incoming_results, qc_nonconformities',
  },
  {
    id: 'qa-lot',
    stream: 'quality',
    title: 'QA LOT Approval Module',
    screens: 'Queue duyet LOT, approve / hold / reject.',
    api: 'POST /api/qa/lot-approvals/:lotId/approve',
    db: 'qa_lot_decisions, qa_lot_decision_reasons',
  },
  {
    id: 'ipc',
    stream: 'quality',
    title: 'IPC Module',
    screens: 'Form QC trong qua trinh, stop-line, incident board.',
    api: 'POST /api/ipc-results/:id/stop-line',
    db: 'ipc_results, ipc_actions',
  },
  {
    id: 'fg-quality',
    stream: 'quality',
    title: 'Finished Goods QC / QA Module',
    screens: 'QC thanh pham, QA duyet batch, ket qua dat / khong dat.',
    api: 'POST /api/qa/fg-approvals/:batchId/approve',
    db: 'fg_qc_results, qa_fg_decisions',
  },
  {
    id: 'work-order',
    stream: 'production',
    title: 'Work Order Module',
    screens: 'Tao lenh, kiem tra dieu kien, dashboard trang thai lenh.',
    api: 'POST /api/work-orders/:id/release',
    db: 'work_orders, work_order_status_logs',
  },
  {
    id: 'batch-record',
    stream: 'production',
    title: 'Batch Record Module',
    screens: 'Phat hanh ho so lo, GMP checklist, khoa dinh muc.',
    api: 'POST /api/batch-records/:id/release',
    db: 'batch_records, batch_record_checklists',
  },
  {
    id: 'execution',
    stream: 'production',
    title: 'Production Execution Module',
    screens: 'Ghi nhan thuc te, hao hut, canh bao lech dinh muc.',
    api: 'POST /api/production-runs/:id/complete-step',
    db: 'production_runs, production_consumptions',
  },
  {
    id: 'packaging',
    stream: 'production',
    title: 'Packaging Module',
    screens: 'Ke hoach dong goi, check bao bi, xac nhan dong goi.',
    api: 'POST /api/packaging-orders/:id/confirm',
    db: 'packaging_orders, packaging_material_checks',
  },
  {
    id: 'fg-warehouse',
    stream: 'production',
    title: 'Finished Goods Warehouse Module',
    screens: 'Nhap kho thanh pham, ton theo batch, lich su xuat nhap.',
    api: 'GET /api/fg-inventory',
    db: 'fg_receipts, fg_inventory_balances',
  },
  {
    id: 'delivery',
    stream: 'closure',
    title: 'Delivery Module',
    screens: 'Tao lenh giao, theo doi giao va xac nhan.',
    api: 'POST /api/deliveries/:id/confirm',
    db: 'deliveries, delivery_confirmations',
  },
  {
    id: 'closure',
    stream: 'closure',
    title: 'Batch Closure Module',
    screens: 'Checklist dong ho so lo, kiem tra thieu chung tu.',
    api: 'GET /api/batch-closures/pending',
    db: 'batch_closures, closure_checklists',
  },
]

export const controlGates: ControlGate[] = [
  {
    type: 'Hard block',
    rule: 'Thieu COA / MSDS / TDS / IFRA, LOT chua QA duyet, IPC fail, batch fail QC.',
  },
  {
    type: 'Soft block',
    rule: 'Hoa don chua FULL khong chan cung, nhung bat buoc canh bao do va CEO duyet ngoai le.',
  },
  {
    type: 'Close gate',
    rule: 'Ho so lo, checklist GMP va chung tu chua du thi khong duoc dong batch.',
  },
]

export const traceabilityChain = [
  'finished_goods',
  'batches',
  'batch_material_issues',
  'material_lots',
  'suppliers',
  'material_documents',
  'invoice_lot_mapping',
  'invoices',
]

export const databaseDomains: DomainCard[] = [
  {
    title: 'Master data',
    description: 'Tach rieng products, materials, suppliers, customers; khong xoa vat ly.',
    tables: ['products', 'materials', 'suppliers', 'customers'],
  },
  {
    title: 'R&D and specs',
    description: 'Version cong thuc, formula items, process va product specs.',
    tables: ['formulas', 'formula_items', 'formula_process', 'product_specs'],
  },
  {
    title: 'LOT and inventory',
    description: 'Quan ly LOT rieng, tai lieu ky thuat, transaction IN/OUT/RETURN/ADJUST.',
    tables: ['material_lots', 'material_documents', 'inventory_transactions'],
  },
  {
    title: 'Invoice control',
    description: 'Theo doi invoice, mapping lot va 3 trang thai FULL / MISSING / EXCESS.',
    tables: ['invoices', 'invoice_items', 'invoice_lot_mapping', 'invoice_status_tracking'],
  },
  {
    title: 'QC / QA',
    description: 'Ket qua incoming, process, final va phe duyet LOT / batch.',
    tables: ['qc_results', 'qa_approvals'],
  },
  {
    title: 'Production and closure',
    description: 'Production order, batch, actual usage, batch record, deviation, CAPA.',
    tables: ['production_orders', 'batches', 'batch_actual_usage', 'batch_records', 'deviations', 'capa'],
  },
]